<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use App\Models\CustomBouquet;
use App\Services\CustomBouquetImageService;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Only run if GD extension is available
        if (!extension_loaded('gd')) {
            \Log::warning('GD extension not available - skipping preview image regeneration');
            return;
        }

        // Get all regular custom bouquets without preview images
        $bouquets = CustomBouquet::where('bouquet_type', 'regular')
            ->where(function($query) {
                $query->whereNull('preview_image')
                      ->orWhere('preview_image', '');
            })
            ->get();

        $imageService = new CustomBouquetImageService();
        $successCount = 0;

        foreach ($bouquets as $bouquet) {
            try {
                $previewPath = $imageService->generateCompositeImage($bouquet);
                
                if ($previewPath && file_exists(storage_path('app/public/' . $previewPath))) {
                    DB::table('custom_bouquets')
                        ->where('id', $bouquet->id)
                        ->update(['preview_image' => $previewPath]);
                    $successCount++;
                }
            } catch (\Exception $e) {
                \Log::warning('Failed to generate preview for bouquet #' . $bouquet->id . ': ' . $e->getMessage());
            }
        }

        \Log::info("Regenerated preview images for {$successCount} custom bouquets");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Cannot reverse - would need to know which previews were generated by this migration
    }
};
